source ENV['GEM_SOURCE'] || 'https://rubygems.org'

gem 'pdqtest', '2.0.0'
gem 'puppet-strings'
gem 'puppet-lint', '2.3.6'
gem 'puppet-syntax', '2.4.1'
gem 'puppetlabs_spec_helper', '2.11.0'
gem 'rake', '12.3.1'
